### ISSUE TITLE
Create Blog post and survey requesting feedback

### ISSUE THREAD

**Issue by erin2722** [MLH-Fellowship/nodemaker#18]
- Post this in the community forum
- Outline the functionality with text and images

**Comment by erin2722** [comment]
Hello everyone,

I am a part of a summer fellowship that is contributing to n8n. After creating a few regular nodes, we found the process to be repetitive and formulaic at times, and so we are creating a tool for the n8n community to generate the code for regular nodes. We are looking for community suggestions and feedback!

A rough draft of mockups is [here](https://www.figma.com/proto/sYzEyTfvGB6i26o2ip8kwf/n8n-nodemaker?node-id=1%3A2&scaling=scale-down). We would love feedback on the UI and the functionality that is outlined [here](https://github.com/ivov/nodemaker/blob/master/README.md) in the README of this project.

Some of the main questions we are considering are:
Would you use this as a CLI tool, a desktop app, or a web app?

**Comment by erin2722** [comment]
@ivov @ianjennings 
I started writing a blog post for the n8n community asking questions about the nodemaker above ^^.
What other questions do we have for the community about this, and what other additional information do you want to give them about out project?

**Comment by ivov** [comment]
Very quick thoughts:

- I'd just say "to make it easier/faster to make the nodes you need" or "to make them more likely to be merged" or something like that, i.e. de-emphasize that the nodemaking process is rather repetitive.

- I'd add two summaries. One with a very short overview of what tasks this app automates, and another based on the README on what files it generates and places on the actual repos.

- I'd add a disclaimer that a web app cannot have placement functionality, so you'll still have to fork the repos and place all the files there yourself.

- I also feel we should clarify that both a desktop app and a webapp will have a CLI, as that's already built into what we're building, and I guess uploading it to NPM will be trivial, i.e. a CLI tool will not be an additional option requiring additional work.

I'll add more after lunch.

**Comment by ivov** [comment]
- Try to think of an eye-catching thread title.
- Ask Jan if he can pin the thread?
- I quickly scraped the most recent 150 threads and the average is 98 views and 6 replies per thread. Keep in mind a plan B in case engagement is low.

**Comment by erin2722** [comment]
### Request for feedback: Node Generator

Hello everyone,

I am a part of a summer fellowship that is contributing to n8n. After creating a few regular nodes, we decided to work on a tool to make it easier to make the nodes you need. We are looking for community suggestions and feedback!

Basically, our application is going to automate the creation of regular nodes (as they are generally just HTTP clients). Specifically, when you input the basics of your node (which resources, operations, and other input fields are needed), the nodemaker will return back the code for this node. This product will simplify node creation and helps PRs get merged faster because the nodemaker takes care of codebase conventions for you.

As long as the nodemaker directory is placed next to the n8n and n8n-docs folders, the nodemaker can generate and place the proper files to add in a new node to n8n. 

These operations are currently supported:

| Script    | Action                                                                                             |
| --------- | -------------------------------------------------------------------------------------------------- |
| `nodegen` | Generate `*.node.ts`, `GenericFunctions.ts`, `*Description.ts` (optional), and `*.credentials.ts`. |
| `packgen` | Generate a `package.json` updated with node path and credential path insertions.                   |
| `docsgen` | Generate a node functionality doc file and a node credential doc file in markdown.                 |
| `icongen` | Generate five images as icon candidates.                         |
| `resize`  | Resize one of the generated icon candidates to a 60×60 px PNG file.                                |
| `place`   | Move files at `/output` to the `n8n` and `n8n-docs` repos.      |

A more detailed description of the nodemaker is [here](https://github.com/ivov/nodemaker/blob/master/README.md).

We would also love feedback on the UI mockups [here](https://www.figma.com/proto/sYzEyTfvGB6i26o2ip8kwf/n8n-nodemaker?node-id=1%3A2&scaling=scale-down).

Some of the main questions we are considering are:
Would you use this as a CLI tool, a desktop app, or a web app?
- The CLI tool will be an easy extension to a desktop or web app.
- We are leaning towards creating a desktop app because a web app will not have the file placement functionality.

Feel free to message me with any questions, comments, or concerns about this project.
