### ISSUE TITLE
Preview Component

### ISSUE THREAD

**Issue by erin2722** [MLH-Fellowship/nodemaker#32]
This one will be tough--

I am planning on grabbing the code that n8n uses to render their nodes and using this in the preview.

Will update later with more info.

![Screen Shot 2020-07-28 at 4 54 30 PM](https://user-images.githubusercontent.com/16248113/88720540-06ec4800-d0f3-11ea-9058-18c428716d63.png)

**Comment by ivov** [comment]
Closed per discussion.
